In [1]:
import numpy as np

In [4]:
a = np.arange(10)  # 0 ~ 9
b = np.array([0, 1, 2, 3, 4])
c = np.array([0, 1, 2, 3, '4'])

In [5]:
print(type(a), a)
print(type(b), b)
print(type(c), c)

<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> [0 1 2 3 4]
<class 'numpy.ndarray'> ['0' '1' '2' '3' '4']


array 형식에는 같은 타입의 자료형만 들어가야함.
이 같은 경우 문자열을 모두 숫자로 바꿀 순 없지만, 숫자는 모두 문자열로 바꿀 수 있기 때문에 문자열로 유연하게 통일시켜버림.

In [9]:
d = a.reshape(2, 5)
print("행렬의 모양: ", d.shape)
print("행렬의 축 갯수: ", d.ndim)
print("행렬 내 원소의 갯수: ", d.size)
d

행렬의 모양:  (2, 5)
행렬의 축 갯수:  2
행렬 내 원소의 갯수:  10


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

1차원 배열을 2차원 배열로 reshape 할때 (10 = 2 * 5)  처럼 갯수가 맞아야함. 갯수가 맞지 않으면 오류가 발생

In [13]:
x = np.array([0, 1, 2, 3, [4, 5], 6], dtype=object)
print(x)
print(type(x))
print(x.dtype)
print(type(x[0]))
print(type(x[4]))

[0 1 2 3 list([4, 5]) 6]
<class 'numpy.ndarray'>
object
<class 'int'>
<class 'list'>


dtype = object 는 객체중 최상위 객체를 뜻함, 즉 array 타입을 다 object 로 지정해서 한 array 에 담음

In [14]:
# 단위행렬 생성하기
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# 0 행렬 생성하기
np.zeros([4, 6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
# 1행렬 생성하기
np.ones([3, 6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### 브로드캐스팅 기법

In [24]:
y = np.arange(9).reshape(3, 3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
y * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [26]:
y + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [27]:
z = np.array([i for i in range(1, 4)])
z

array([1, 2, 3])

In [31]:
# 행렬끼리 계산 (3 X 3) + (1 X 3)
print(y)
print(z)
y + z

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]


array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [32]:
# (3 X 3) + (3 X 1)
k = np.array([[1], [2], [3]])
print(y)
print(k)
y + k

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [2]
 [3]]


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

행렬간 계산에서 행렬끼리 사이즈가 맞지 않으면 오류가 발생

In [33]:
# 간단한 리스트와 어레이의 차이
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [34]:
print(np.array([1, 2]) + np.array([3, 4]))
print(np.array([1, 2]) + 3)

[4 6]
[4 5]


### 슬라이스, 인덱싱

In [35]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
print(y)
y[1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3, 4, 5])

In [40]:
y[2, 0]  # 3번째 에서 1번째 값

6

In [41]:
y[2][0]

6

In [43]:
print(y[:-1])
y[:-1]  # -1까지니까, -1을 제외하고 모두

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
y[:, 2:]  # 열로 인덱싱 슬라이스 하기

array([[2],
       [5],
       [8]])

In [56]:
y[:, :-1]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [57]:
y[1, 2:]  # 행 열 동시 인덱싱 슬라이스

array([5])

In [58]:
y[:2, 1:]  # 0,1행, 1열부터

array([[1, 2],
       [4, 5]])

In [59]:
y[:, -1]

array([2, 5, 8])

### numpy 의사 난수 기능

In [62]:
print(np.random.random())  # 0에서 1사이 실수형 난수 하나 생성
print(np.random.randint(0, 10))  # 0에서 10 사이 정수형 난수 하나 생성
print(np.random.choice([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))  # 리스트에 주어진 값 중 하나를 랜덤하게 고름

0.31600586936822883
7
8


In [66]:
t = np.random.permutation(10)  # 파라미터값의 범위 내에서 무작위로 섞인 배열(array)을 생성
print(t)
type(t)

[1 7 6 2 9 4 3 5 8 0]


numpy.ndarray

In [68]:
# 정규분포와 균등분포 에 따른 무작위 값 생성하기
print(np.random.normal(loc=10, scale=2, size=6))  # 평균(loc), 표준편차(scale), 갯수(size) - 정규 분포
print(np.random.uniform(low=1, high=5, size=4))  # 최솟값(low), 최댓값(high), 갯수(size) - 균등 분포

[11.20934118  8.77159433 10.35842508  9.58758469  7.55843133  7.89226883]
[1.53757533 3.00323143 4.74040877 4.99919871]


### 전치행렬

In [74]:
px = np.arange(24).reshape(2,3,4)
px

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
px.shape

(2, 3, 4)

In [80]:
px.T  # 행과 열 맞바꾸기 (replace필요)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [81]:
px.T.shape

(4, 3, 2)

In [85]:
# 행렬의 축을 지정할 수 있는 행렬 전치 함수
py = np.transpose(px, (2, 0, 1))  # 2,3,4 의 순서를 인덱스 기법으로 지정
print(px.shape)
print(py.shape)
py

(2, 3, 4)
(4, 2, 3)


array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])